### ISSUE TITLE
Security problem / Project maintenance status?

### ISSUE THREAD

**Issue by pataquets** [aurc/loggo#21]
Hi @aurc.
Thanks for sharing this fine piece of software.
As I've found in a fork of your repo, there is allegedlly a security vulnerability which you might have not noticed.
Link to relevant commit in fork:
[Bump go version to 1.21 everywhere, update vulnerable dependencies · Egor3f/loggo@2c5094e](https://github.com/Egor3f/loggo/commit/2c5094e2eaa3effe0e11aca3874d4a552b5a0b3a)

Also, that leads me to wonder if the program is still maintained, if you're interested/able/etc to keep it or if you are no longer interested/able/etc (which would be prefectly fine in any case). However, if the latter is true, I'd like to suggest to post some sort of "seeking new maintainer (or co-maintainer)", or whatever formula you find appropriate to prevent this software to end up abandoned. There is also https://adoptoposs.org to post it.

In any case, thanks for sharing your work.

**Comment by aurc** [comment]
Hi @pataquets
Thanks for the bump! Can't believe how long has passed since the last update. I have updated all to the latest and greatest. Keep me posted if you have any feature requests!
Cheers
Aurelio

**Comment by aurc** [comment]
Fixed - enabled auto vulnerability PRs
